config/routes.rb
Moviebusapp::Application.routes.draw do

  get "comments/home"
  get "comments/delete"
  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"
  get "theatres/show"
  
  resources :users

    namespace :api, defaults: {format: 'xml' } do
		namespace :v1 do
			resources :theatres
		end
	end
	resources :movies
	resources :theatres
	resources :locations
	
	root to: 'users#new'
	

  

end

app/models/location.rb
class Location < ActiveRecord::Base
attr_accessible :areaename
	def self.search(search)
		if search
			find(:all, :conditions => ['areaname LIKE ?', "%#{search}%"])
			
		else
			find(:all)
		end
	end
	
	has_many :theatres
	belongs_to:theatre
end

app/models/movie.rb
class Movie < ActiveRecord::Base
attr_accessible :moviename, :theatrenumber, :theatre_id
def self.search(search)
		if search
			find(:all, :conditions => ['moviename LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end
	
	
	belongs_to :theatre
	
end

app/models/theatre.rb
class Theatre < ActiveRecord::Base
attr_accessible :theatrename, :moviename, :location_id
def self.search(search)
		if search
			find(:all, :conditions => ['theatrename LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end
	
	
	has_many :movies
	belongs_to :location
	has_many :locations
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :name, :password, :password_confirmation, :username
	has_secure_password

	validates :username, uniqueness: true, presence: true
	validates :email, uniqueness: true, presence: true
	has_many :comments
end

app/controllers/api/v1/theatres_controller.rb
module Api
	module V1
		class TheatresController < ApplicationController
			respond_to :xml
			
			def index
				respond_with Theatre.search(params[:search])	
			end
			
			def show
			    respond_with Theatre.search(params[:search])
			end
			
			def new
				respond_with Theatre.new
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  
  private
  def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
 
  helper_method :current_user
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def home
  end

  def delete
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
 def new
   @location= Location.new
 end

  def create
   @location = Location.new(location_params)
		if @location.save
			redirect_to new_location_path, notice: "Thank you for adding a movie!"
		else
			render 'new'
		end
   end
   
   
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	
    def location_params
		params.require(:location).permit(:areaename)
	end
	
	def show
		@location = Location.new
		@locations = Location.search(params[:search])
		
	end
	
	
	def index
		@location = Location.new
		@locations = Location.search(params[:search])

	end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	
	
	def new
		@movie = Movie.new
		
	end
	
	def create
		@movie = Movie.new(params[:movie])
		if @movie.save
			redirect_to new_movie_path, notice: "Thank you for adding a movie!"
		else
			render 'new'
		end
	end
	
	def movie_params
		params.require(:movie).permit(:moviename,:theatrenumber)
	end
	
	def show
		@movie = Movie.new
		@movies = Movie.search(params[:search])
		
	end
	
	
	def index
		@movie = Movie.new
		@movies = Movie.search(params[:search])

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
        session[:userid] = user.id
        redirect_to new_movie_path, notice: "Logged in!"
    else
        flash[:error] = "Wrong Username or Password."
        redirect_to new_user_path
    end
  end
  
  def destroy
	session[:userid] = nil
    redirect_to new_user_path, notice: "Logged out."
  end
end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
	def new
		@theatre = Theatre.new
		
	end
	
	def create
		@theatre = Theatre.new(params[:theatre])
		respond_to do |format|  
			if @theatre.save
				format.html { redirect_to new_theatre_path, :notice => 'Thank you for adding a theatre!' } 
				#redirect_to new_movie_path, notice: "Thank you for adding a theatre!"
				format.js
				#render :partial => 'theatre', :object => @theatre
				
			else
				#render 'new'
				format.html { render :action => "new" }  
				format.js
			end
		end
	end
	
	def theatre_params
		params.require(:movie).permit(:theatrename,:moviename)
	end
	
	def show
		@theatre = Theatre.new
		@theatres = Theatre.search(params[:search])
		
	end
	
	
	def index
		@theatre = Theatre.new
		@theatres = Theatre.search(params[:search])
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	
	def create
	@user = User.new(params[:user])
 
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: "Thank you for signing up to moviebus!"			
		else
			render 'new'
		end
	end
	
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/home.html.erb
<h1>Comments#home</h1>
<p>Find me in app/views/comments/home.html.erb</p>

app/views/locations/show.html.erb
<header>
	<div>
		<p style ="padding:10px;"></p>
	</div>
	
	<% if current_user %>
    <%= link_to "Log Out", sessions_destroy_path %>
	<% end %>
	
 </header>
<div id="findLocation" class="panel left">
    <h1>Find a theatre in your location</h1>
	<%= form_tag location_path, :method => 'get' do %>
		<p>
			<%= text_field_tag :search, params[:search] %>
			<%= submit_tag "Search", :name=>nil %>   
    
		</p>
	<% end %>
</div>

  

<div class="panel left">
    <h1>Your Theatres </h1>
    <div class="movieWrapper">
        Display all theatres in your area <br />
			<% if @locations %>
				<%  @locations.each do |item| %>
					closest theatre in <%= item.areaname %> is <%= item.theatre.theatrename %>
					
				<% end %>
				
					  
			

			<% end %>
    </div>
</div>

app/views/movies/index.html.erb
<div id="findMovie" class="panel left">
    <h1>Find a movie</h1>
	<%= form_tag movies_path, :method => 'get' do %>
		<p>
			<%= text_field_tag :search, params[:search] %>
			<%= submit_tag "Search", :name=>nil %>   
    
		</p>
	<% end %>
</div>

<div class="panel left">
    <h1>Your Movies</h1>
    <div class="movieWrapper">
        Display all movie information <br />
			<% if !@movies.blank? %>
				<% for item in @movies %>
					<%= item.moviename %> <%= item.theatrenumber %> <%= item.theatres.theatrename %> <br />
				<% end %>
			<% else %>

			<% end %>
    </div>
</div>

app/views/movies/new.html.erb
 <header>
	<div>
		<p style ="padding:10px;"></p>
	</div>
	<div style= "margin-left: 740px;">
	<% if current_user %>
    <%= link_to "Log Out", sessions_destroy_path %>
	<% end %>
	</div>
 </header>
<div class="panel right">
  <h1>Add a movie playing at a theatre near you</h1>
   
  <%= form_for @movie do |f| %>
    <% if @movie.errors.any? %>
      <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
 
    <%= f.text_field :moviename, placeholder: "moviename" %>
    <%= f.text_field :theatrenumber, placeholder: "Screen number" %>
	<%= f.text_field :theatre_id, placeholder: "1 for imax,3 for amc ,10 for Pear avenue" %>
    <%= f.submit "Submit" %>
  
  <% end %>
 
</div>

<div class="panel left">
  <h1 style = "padding: 40px;"><a href="http://localhost:3000/theatres/new">Add a theatre</a></h1>
  <h1 style = "padding: 40px;"><a href="http://localhost:3000/movies/show?utf8=%E2%9C%93&search=jobs">Search a theatre playing your favourite movie</a></h1> 
  <h1 style = "padding: 40px;"><a href="http://localhost:3000/theatres/index">Search a movie at your favourite theatre</a> </h1> 
  <h1 style = "padding: 40px;"><a href="http://localhost:3000/locations/show">Enter your location to find the theatre nearest you</a> </h1> 
</div>

app/views/movies/show.html.erb
<header>
	<div>
		<p style ="padding:10px;"></p>
	</div>
	
	<% if current_user %>
    <%= link_to "Log Out", sessions_destroy_path %>
	<% end %>
	
 </header>
<div id="findMovie" class="panel left">
    <h1>Find a movie</h1>
	<%= form_tag movie_path, :method => 'get' do %>
		<p>
			<%= text_field_tag :search, params[:search] %>
			<%= submit_tag "Search", :name=>nil %>   
    
		</p>
	<% end %>
</div>

  

<div class="panel left">
    <h1>Your Movies </h1>
    <div class="movieWrapper">
        Display all movie information <br />
			<% if @movies %>
				<%  @movies.each do |item| %>
					<%= item.moviename %> is running in screen 
					<%=  item.theatrenumber %> at  <%=  item.theatre.theatrename %> 
					
				<% end %>
				
					  
			

			<% end %>
    </div>
</div>

app/views/theatres/create.js.erb
$('body').html("<h1><%= escape_javaScript(@theatre.theatrename) %></h1>").append("<%= escape_javaScript(@theatre.moviename) %>"); 

app/views/theatres/index.html.erb
<header>
	<div>
		<p style ="padding:10px;"></p>
	</div>
	<div style= "margin-left: 740px;">
	<% if current_user %>
    <%= link_to "Log Out", sessions_destroy_path %>
	<% end %>
	</div>
 </header>
<div id="findtheatre" class="panel left">
    <h1>Find a theatre</h1>
	<%= form_tag theatres_path, :method => 'get' do %>
		<p>
			<%= text_field_tag :search, params[:search] %>
			<%= submit_tag "Search", :name=>nil %>   
    
		</p>
	<% end %>
</div>

<div class="panel left">
    <h1>Your Theatres</h1>
    <div class="movieWrapper">
        Display all theatre information <br />
			<% if !@theatres.blank? %>
				<% for item in @theatres %>
					<%= item.theatrename %>   Is currently playing   <%= item.moviename %> <br />
				<% end %>
			<% else %>

			<% end %>
    </div>
</div>

app/views/theatres/new.html.erb
<header>
	<div>
		<p style ="padding:0px;"></p>
	</div>
	
 </header>
 <% if current_user %>
 <%= link_to "Log Out", sessions_destroy_path, remote=>true %>
<% end %>

<div class="panel left">
  <h1>Add a Theatre</h1>
   
  <%= form_for(@theatre, :remote => true) do |f| %>
    <% if @theatre.errors.any? %>
      <ul>
        <% @theatre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
 
    <%= f.text_field :theatrename, placeholder: "theatrename" %> 
    <%= f.text_field :moviename, placeholder: "moviename" %>
    <div><%= f.submit "Submit" %></div>
  
  <% end %>
</div>

app/views/theatres/show.html.erb
<header>
	<div>
		<p style ="padding:10px;"></p>
	</div>
	<div style= "margin-left: 740px;">
	<% if current_user %>
    <%= link_to "Log Out", sessions_destroy_path %>
	<% end %>
	</div>
 </header>
<div id="findtheatre" class="panel left">
    <h1>Find a theatre</h1>
	<%= form_tag theatres_path, :method => 'get' do %>
		<p>
			<%= text_field_tag :search, params[:search] %>
			<%= submit_tag "Search", :name=>nil %>   
    
		</p>
	<% end %>
</div>

<div class="panel left">
    <h1>Your Theatres</h1>
    <div class="movieWrapper">
        Display all theatre information <br />
			<% if !@theatres.blank? %>
				<% for item in @theatres %>
					<%= item.theatrename %>  Is currently playing <%= item.moviename %> <br />

				    <% end %>
			<% else %>
                    <%= puts "  hi  " %>
			<% end %>
    </div>
</div>

app/views/users/new.html.erb
<header>
        <div class="wrapper" >
            <!--<img src="/gfx/p1.jpg">-->
			<%= form_tag sessions_create_path do %>
				<%= text_field_tag :username, nil, placeholder: "username" %>
				<%= password_field_tag :password, nil,  placeholder: "password" %>
				<%= submit_tag "Log In" %>
    
			<% end %>
        </div>
    </header>
<img src="/gfx/At-the-movies.jpg">


 
<div class="panel right">
  <h1> Sign Up </h1>
   
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
 
    <%= f.text_field :email, placeholder: "email" %>
    <%= f.text_field :username, placeholder: "username" %>
    
    <%= f.password_field :password, placeholder: "password" %>
    <%= f.password_field :password_confirmation, placeholder: "password" %>
    <%= f.submit "Create Account" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="createRibbit" class="panel right">
    <h1> </h1>
    <p>
    <form>
        <textarea name="text" class="ribbitText"></textarea>
        <input type="submit" value="Submit">
    </form>
    </p>
</div>
<div id="ribbits" class="panel left">
    <h1>Your Moviebus  Profile</h1>
    <div class="ribbitWrapper">
        

        
    </div>
</div>
<div class="panel left">
    <h1>Your Comments</h1>
    <div class="ribbitWrapper">
        
    </div>
</div>